import type { AppTemplate } from "./types";

export const TEMPLATES: AppTemplate[] = [
  {
    id: "web-app",
    name: "Web App",
    description: "Full-stack web application with modern UI",
    icon: "globe",
    defaultPhases: [
      "research",
      "planning",
      "architecture",
      "implementation",
      "testing",
      "polish",
    ],
    suggestedStack: ["Next.js", "TypeScript", "Tailwind", "SQLite"],
    promptHint: "Describe the product and primary user flows",
  },
  {
    id: "cli-tool",
    name: "CLI Tool",
    description: "Command-line utility with clear UX",
    icon: "terminal",
    defaultPhases: [
      "research",
      "planning",
      "architecture",
      "implementation",
      "testing",
      "polish",
    ],
    suggestedStack: ["TypeScript", "Node.js", "Commander", "Ink"],
    promptHint: "What commands should it expose and who is the user?",
  },
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Ops / analytics control panel",
    icon: "layout-dashboard",
    defaultPhases: [
      "research",
      "planning",
      "architecture",
      "implementation",
      "testing",
      "polish",
    ],
    suggestedStack: ["React", "Recharts", "TanStack Query", "Tailwind"],
    promptHint: "What metrics and actions should operators see?",
  },
  {
    id: "api-service",
    name: "API Service",
    description: "Backend API with auth and persistence",
    icon: "server",
    defaultPhases: [
      "research",
      "planning",
      "architecture",
      "implementation",
      "testing",
      "polish",
    ],
    suggestedStack: ["Hono", "PostgreSQL", "Zod", "OpenAPI"],
    promptHint: "List resources, auth model, and SLAs",
  },
  {
    id: "agent-workflow",
    name: "Agent Workflow",
    description: "Multi-agent automation pipeline",
    icon: "bot",
    defaultPhases: [
      "research",
      "planning",
      "architecture",
      "implementation",
      "testing",
      "polish",
    ],
    suggestedStack: ["TypeScript", "Queue", "Vector store", "LLM APIs"],
    promptHint: "What should agents collaborate on end-to-end?",
  },
  {
    id: "mobile-app",
    name: "Mobile App",
    description: "Cross-platform mobile experience",
    icon: "smartphone",
    defaultPhases: [
      "research",
      "planning",
      "architecture",
      "implementation",
      "testing",
      "polish",
    ],
    suggestedStack: ["React Native", "Expo", "TypeScript"],
    promptHint: "Core screens and offline needs",
  },
];
