import type { Agent } from "../types";

export const DEFAULT_AGENTS: Agent[] = [
  {
    id: "agent-hermes",
    name: "Hermes",
    slug: "hermes",
    type: "local",
    roles: ["researcher", "generalist", "planner"],
    status: "idle",
    capabilities: [
      "local-cli",
      "web-research",
      "tool-use",
      "multi-step-reasoning",
    ],
    strengths: {
      research: 92,
      planning: 78,
      architecture: 65,
      implementation: 60,
      testing: 55,
      polish: 50,
      brainstorm: 85,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Local Hermes agent — strong researcher and generalist for on-device workflows.",
    model: "hermes-default",
    config: {
      enabled: true,
      systemPrompt:
        "You are Hermes, a precise research and planning agent. Prefer primary sources and clear structure.",
      toolAccess: ["fs", "shell", "web"],
      maxConcurrent: 2,
    },
    metrics: {
      tokensUsed: 128_400,
      avgLatencyMs: 820,
      successRate: 0.94,
      tasksCompleted: 47,
      tasksFailed: 3,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-claude-code",
    name: "Claude Code",
    slug: "claude-code",
    type: "cloud",
    roles: ["coder", "architect", "tester"],
    status: "idle",
    capabilities: [
      "code-generation",
      "refactoring",
      "repo-aware",
      "tests",
      "cli",
    ],
    strengths: {
      research: 70,
      planning: 82,
      architecture: 95,
      implementation: 96,
      testing: 88,
      polish: 90,
      brainstorm: 80,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Claude Code — elite architecture and implementation for complex codebases.",
    model: "claude-opus",
    config: {
      enabled: true,
      apiKeyEnv: "ANTHROPIC_API_KEY",
      systemPrompt:
        "You are Claude Code. Write production-quality, well-tested software with clear architecture.",
      toolAccess: ["fs", "shell", "git", "tests"],
      maxConcurrent: 1,
    },
    metrics: {
      tokensUsed: 412_000,
      avgLatencyMs: 1450,
      successRate: 0.97,
      tasksCompleted: 89,
      tasksFailed: 2,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-codex",
    name: "Codex",
    slug: "codex",
    type: "cloud",
    roles: ["coder", "tester", "architect"],
    status: "idle",
    capabilities: [
      "code-generation",
      "pair-programming",
      "tests",
      "fast-iteration",
    ],
    strengths: {
      research: 60,
      planning: 70,
      architecture: 80,
      implementation: 94,
      testing: 90,
      polish: 75,
      brainstorm: 72,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "OpenAI Codex — fast implementation and solid test coverage.",
    model: "codex",
    config: {
      enabled: true,
      apiKeyEnv: "OPENAI_API_KEY",
      systemPrompt:
        "You are Codex. Implement features quickly with clean interfaces and thorough tests.",
      toolAccess: ["fs", "shell", "git", "tests"],
      maxConcurrent: 2,
    },
    metrics: {
      tokensUsed: 298_500,
      avgLatencyMs: 980,
      successRate: 0.93,
      tasksCompleted: 112,
      tasksFailed: 8,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-grok",
    name: "Grok",
    slug: "grok",
    type: "cloud",
    roles: ["planner", "researcher", "critic", "generalist"],
    status: "idle",
    capabilities: [
      "reasoning",
      "brainstorm",
      "critique",
      "planning",
      "real-time-knowledge",
    ],
    strengths: {
      research: 88,
      planning: 93,
      architecture: 78,
      implementation: 70,
      testing: 65,
      polish: 72,
      brainstorm: 98,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Grok (SpaceXAI/xAI) — creative brainstorming, planning, and sharp critique.",
    model: "grok-4.5",
    config: {
      enabled: true,
      apiKeyEnv: "XAI_API_KEY",
      systemPrompt:
        "You are Grok. Be maximally helpful, creative, and direct. Challenge weak ideas and strengthen good ones.",
      toolAccess: ["web", "reasoning"],
      maxConcurrent: 3,
    },
    metrics: {
      tokensUsed: 521_200,
      avgLatencyMs: 1100,
      successRate: 0.95,
      tasksCompleted: 134,
      tasksFailed: 6,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-antigravity",
    name: "Antigravity",
    slug: "antigravity",
    type: "cloud",
    roles: ["coder", "planner", "generalist"],
    status: "idle",
    capabilities: [
      "code-generation",
      "repo-aware",
      "agent-cli",
      "multi-agent",
      "brainstorm",
    ],
    strengths: {
      research: 82,
      planning: 88,
      architecture: 86,
      implementation: 90,
      testing: 80,
      polish: 82,
      brainstorm: 88,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Google Antigravity (`agy`) — terminal agent harness for coding and idea generation.",
    model: "agy",
    config: {
      enabled: true,
      systemPrompt:
        "You are Antigravity. Plan clearly, use tools carefully, and implement reviewable changes.",
      toolAccess: ["fs", "shell", "git", "tests"],
      maxConcurrent: 1,
    },
    metrics: {
      tokensUsed: 0,
      avgLatencyMs: 1300,
      successRate: 0.94,
      tasksCompleted: 0,
      tasksFailed: 0,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-lmstudio-qwen",
    name: "LM Studio · Qwen",
    slug: "lmstudio-qwen",
    type: "local",
    roles: ["coder", "generalist"],
    status: "idle",
    capabilities: ["local-inference", "offline", "code", "chat"],
    strengths: {
      research: 55,
      planning: 60,
      architecture: 62,
      implementation: 78,
      testing: 70,
      polish: 68,
      brainstorm: 65,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Qwen3 Coder 30B (MLX 4-bit) via LM Studio — private, offline-capable coding.",
    model: "lmstudio-community/Qwen3-Coder-30B-A3B-Instruct-MLX-4bit",
    config: {
      enabled: true,
      systemPrompt: "You are a local coding assistant running via LM Studio.",
      toolAccess: ["fs"],
      modelOverride:
        "lmstudio-community/Qwen3-Coder-30B-A3B-Instruct-MLX-4bit",
      maxConcurrent: 1,
    },
    metrics: {
      tokensUsed: 89_000,
      avgLatencyMs: 2100,
      successRate: 0.88,
      tasksCompleted: 31,
      tasksFailed: 4,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-lmstudio-llama",
    name: "LM Studio · Llama",
    slug: "lmstudio-llama",
    type: "local",
    roles: ["researcher", "generalist", "critic"],
    status: "idle",
    capabilities: ["local-inference", "offline", "analysis", "chat"],
    strengths: {
      research: 72,
      planning: 68,
      architecture: 55,
      implementation: 58,
      testing: 60,
      polish: 62,
      brainstorm: 74,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Local Llama via LM Studio — private analysis and secondary critique.",
    model: "llama-3.3-70b",
    config: {
      enabled: true,
      systemPrompt: "You are a careful local analyst. Be thorough and skeptical.",
      toolAccess: ["fs"],
      modelOverride: "llama-3.3-70b",
      maxConcurrent: 1,
    },
    metrics: {
      tokensUsed: 64_200,
      avgLatencyMs: 3200,
      successRate: 0.9,
      tasksCompleted: 22,
      tasksFailed: 2,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-lmstudio-gemma4",
    name: "LM Studio · Gemma 4 31B",
    slug: "lmstudio-gemma4",
    type: "local",
    roles: ["generalist", "researcher", "coder"],
    status: "idle",
    capabilities: [
      "local-inference",
      "offline",
      "chat",
      "multimodal",
      "vision",
      "code",
    ],
    strengths: {
      research: 80,
      planning: 74,
      architecture: 72,
      implementation: 76,
      testing: 70,
      polish: 75,
      brainstorm: 82,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Gemma 4 31B IT QAT (GGUF) via LM Studio — strong local generalist with vision support.",
    model: "lmstudio-community/gemma-4-31B-it-QAT-GGUF",
    config: {
      enabled: true,
      systemPrompt:
        "You are Gemma 4 running locally via LM Studio. Be clear, capable, and practical across research, coding, and analysis.",
      toolAccess: ["fs"],
      modelOverride: "lmstudio-community/gemma-4-31B-it-QAT-GGUF",
      maxConcurrent: 1,
    },
    metrics: {
      tokensUsed: 0,
      avgLatencyMs: 2400,
      successRate: 0.92,
      tasksCompleted: 0,
      tasksFailed: 0,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-lmstudio-nemotron",
    name: "LM Studio · Nemotron Omni",
    slug: "lmstudio-nemotron",
    type: "local",
    roles: ["planner", "researcher", "critic", "generalist"],
    status: "idle",
    capabilities: [
      "local-inference",
      "offline",
      "reasoning",
      "multimodal",
      "chat",
      "analysis",
    ],
    strengths: {
      research: 86,
      planning: 90,
      architecture: 78,
      implementation: 68,
      testing: 72,
      polish: 70,
      brainstorm: 84,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Nemotron 3 Nano Omni 30B Reasoning (GGUF) via LM Studio — local reasoning and planning specialist.",
    model:
      "lmstudio-community/nemotron-3-nano-omni-30b-a3b-reasoning-gguf",
    config: {
      enabled: true,
      systemPrompt:
        "You are Nemotron Omni, a careful local reasoning agent. Prefer structured plans, explicit tradeoffs, and rigorous critique.",
      toolAccess: ["fs", "reasoning"],
      modelOverride:
        "lmstudio-community/nemotron-3-nano-omni-30b-a3b-reasoning-gguf",
      maxConcurrent: 1,
    },
    metrics: {
      tokensUsed: 0,
      avgLatencyMs: 2800,
      successRate: 0.93,
      tasksCompleted: 0,
      tasksFailed: 0,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-lmstudio-glm46v",
    name: "LM Studio · GLM-4.6V Flash",
    slug: "lmstudio-glm46v",
    type: "local",
    roles: ["generalist", "coder", "researcher"],
    status: "idle",
    capabilities: [
      "local-inference",
      "offline",
      "vision",
      "multimodal",
      "fast-iteration",
      "chat",
      "code",
    ],
    strengths: {
      research: 76,
      planning: 72,
      architecture: 70,
      implementation: 80,
      testing: 74,
      polish: 78,
      brainstorm: 79,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "GLM-4.6V Flash (MLX 4-bit) via LM Studio — fast local multimodal model for chat, vision, and coding.",
    model: "lmstudio-community/GLM-4.6V-Flash-MLX-4bit",
    config: {
      enabled: true,
      systemPrompt:
        "You are GLM-4.6V Flash running locally via LM Studio. Be fast, precise, and multimodal-aware.",
      toolAccess: ["fs"],
      modelOverride: "lmstudio-community/GLM-4.6V-Flash-MLX-4bit",
      maxConcurrent: 1,
    },
    metrics: {
      tokensUsed: 0,
      avgLatencyMs: 1600,
      successRate: 0.91,
      tasksCompleted: 0,
      tasksFailed: 0,
    },
    lastSeenAt: new Date().toISOString(),
  },
  // ── OpenJarvis (https://github.com/open-jarvis/OpenJarvis) ──────────────
  {
    id: "agent-jarvis",
    name: "OpenJarvis",
    slug: "jarvis",
    type: "local",
    roles: ["generalist", "planner", "researcher", "coder"],
    status: "offline",
    capabilities: [
      "openjarvis",
      "local-first",
      "tool-use",
      "orchestrator",
      "memory",
      "openai-compatible-api",
      "cli",
    ],
    strengths: {
      research: 90,
      planning: 88,
      architecture: 82,
      implementation: 84,
      testing: 78,
      polish: 76,
      brainstorm: 86,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "Jarvis hybrid chat — LM Studio (Hermes) for private turns, Grok + Tavily for live data; OpenJarvis serve/CLI for pipeline tools.",
    model: "gulan28/Hermes-3-Llama-3.1-8B-abliterated-GGUF",
    config: {
      enabled: true,
      systemPrompt:
        "You are Jarvis — a personal AI assistant inside Cortex. Private chat may run on local Hermes via LM Studio; live/current questions may use Grok with web results. Prefer Live web results and the clock over training memory. Speak clearly and helpfully.",
      toolAccess: ["fs", "shell", "web", "memory", "tools"],
      maxConcurrent: 2,
      extras: { jarvisAgent: "simple" },
    },
    metrics: {
      tokensUsed: 0,
      avgLatencyMs: 900,
      successRate: 0.94,
      tasksCompleted: 0,
      tasksFailed: 0,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-jarvis-research",
    name: "Jarvis · Research",
    slug: "jarvis-research",
    type: "local",
    roles: ["researcher", "generalist"],
    status: "idle",
    capabilities: [
      "openjarvis",
      "deep-research",
      "citations",
      "memory",
      "web-research",
      "local-first",
    ],
    strengths: {
      research: 96,
      planning: 75,
      architecture: 60,
      implementation: 55,
      testing: 50,
      polish: 58,
      brainstorm: 80,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "OpenJarvis deep_research agent — multi-hop research with citations across web and indexed local docs.",
    model: "gulan28/Hermes-3-Llama-3.1-8B-abliterated-GGUF",
    config: {
      enabled: true,
      systemPrompt:
        "You are OpenJarvis deep research. Multi-hop investigation with citations. Be thorough and source-aware.",
      toolAccess: ["web", "memory", "retrieval"],
      maxConcurrent: 1,
      extras: { jarvisAgent: "deep_research" },
    },
    metrics: {
      tokensUsed: 0,
      avgLatencyMs: 2400,
      successRate: 0.92,
      tasksCompleted: 0,
      tasksFailed: 0,
    },
    lastSeenAt: new Date().toISOString(),
  },
  {
    id: "agent-jarvis-code",
    name: "Jarvis · Code",
    slug: "jarvis-code",
    type: "local",
    roles: ["coder", "architect", "tester"],
    status: "offline",
    capabilities: [
      "openjarvis",
      "code-assistant",
      "code-execution",
      "file-io",
      "shell",
      "local-first",
    ],
    strengths: {
      research: 70,
      planning: 78,
      architecture: 88,
      implementation: 92,
      testing: 86,
      polish: 80,
      brainstorm: 72,
    },
    currentTaskId: null,
    currentTaskLabel: null,
    description:
      "OpenJarvis code-assistant / orchestrator — code execution, file I/O, and shell for implementation work.",
    model: "gulan28/Hermes-3-Llama-3.1-8B-abliterated-GGUF",
    config: {
      enabled: true,
      systemPrompt:
        "You are OpenJarvis code assistant. Write production-quality code, use tools carefully, and explain tradeoffs briefly.",
      toolAccess: ["fs", "shell", "code"],
      maxConcurrent: 1,
      extras: { jarvisAgent: "orchestrator" },
    },
    metrics: {
      tokensUsed: 0,
      avgLatencyMs: 1800,
      successRate: 0.91,
      tasksCompleted: 0,
      tasksFailed: 0,
    },
    lastSeenAt: new Date().toISOString(),
  },
];
